version: "3"

services:
  database:
    container_name: movies_database
    image: postgres:13
    volumes:
      - ./schema_design/db_schema.sql:/docker-entrypoint-initdb.d/10-init.sql
      - movies_database_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
    restart: always
  web:
    container_name: movies_admin
    build:
      context: .
      dockerfile: ./movies_admin/Dockerfile
    env_file:
      - ./movies_admin/.env
    volumes:
      - ./movies_admin:/app
    entrypoint:
      - "python"
      - "entrypoint.py"
    restart: always
    depends_on:
      - database
  transfer:
    container_name: movies_transfer
    restart: on-failure
    build:
      context: ./sqlite_to_postgres
      dockerfile: ./Dockerfile
    volumes:
      - ./sqlite_to_postgres:/app
    env_file:
      - ./sqlite_to_postgres/.env
    entrypoint:
      - "python"
      - "load_data.py"
    depends_on:
      - web
  nginx:
    container_name: movies_proxy
    restart: always
    image: nginx:1.19.2
    volumes:
      - ./src/nginx.conf:/etc/nginx/nginx.conf
      - ./src/site.conf:/etc/nginx/conf.d/site.conf
      - ./movies_admin/static:/data/static
      - ./movies_admin/media:/data/media
    depends_on:
      - web
    ports:
      - "80:80"

volumes:
  movies_database_data:
